config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  devise_for :users
  get 'welcome/index'

  resources :loudnessmeasures
  resources :mediafiles

  root 'welcome#index'

end

app/models/loudness_measure.rb
require 'fog'
require 'uri'

class LoudnessMeasure < ActiveRecord::Base

  belongs_to :user

  validates :state, presence: true
  validates :name, presence: true
  validates :url, presence: true, length: { minimum: 3 }

  def self.getloudnessmeasuresqueuedtoprocess
    loudnessmeasure = nil

    ActiveRecord::Base.transaction do
      #Returns first in queued state
      loudnessmeasure = LoudnessMeasure.find_by(state: 'queued')
      if(loudnessmeasure.present?)
        loudnessmeasure.updatestate 'processing'
      end
    end

    loudnessmeasure
  end

  def updatestate (newstate)
    update ({:state => newstate})
  end

  def updateloudnessvalues (i, lra)
    update ({:loudnessi => i, :loudnesslra => lra})
  end

  def updatelocalfilename (filename)
    update ({:localfilename => filename})
  end

  def filename
    File.basename url
  end

  def filename_plain
    File.basename(url.gsub("%2F","/"))
  end

  def filepath
    uri = URI::parse(url)
    uri.path[0] = ""

    uri.path
  end

  def filepath_plain
    filepath.gsub("%2F","/")
  end

  def bucketname
    s = url.scan /.*\/\/(.*)\.s3.*/
    s.first.first
  end

  def url_plain
    url.gsub("%2F","/")
  end

  def downloadfroms3 (localfile, acceskey, secretkey, default_region)
    connection = Fog::Storage.new({
      :provider                 => 'AWS',
      :aws_access_key_id        => acceskey,
      :aws_secret_access_key    => secretkey,
      :region => default_region})

    bucket = connection.directories.get(bucketname)

    #TODO: Add while bexit == false
    open(localfile, 'wb') do |f|
      bucket.files.get(filepath_plain) do |chunk,remaining_bytes,total_bytes|
        #puts "Rem: #{remaining_bytes}, Total: #{total_bytes}"
        f.write chunk
      end
      f.close
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/loudnessmeasures_controller.rb
class LoudnessmeasuresController < ApplicationController

	@loudnessmeasure = nil
	@loudnessmeasures = nil

	def new
		@loudnessmeasure = LoudnessMeasure.new()
	end
	
	def create
  		@loudnessmeasure = LoudnessMeasure.new(loudnessmeasure_params_to_db)
 
  		if @loudnessmeasure.save
			render :action => 'show', :id => @loudnessmeasure.id
		else
			render 'new'
		end 
 	end
	
	def show
		#TODO: improve (if null?)
  		@loudnessmeasure = LoudnessMeasure.where("id = #{params[:id]} AND user_id = #{current_user.id}").first
 	end

	def index
		#TODO: improve
  		@loudnessmeasures = LoudnessMeasure.where("user_id = #{current_user.id}")
	end

private 

 	def loudnessmeasure_params_to_db
		params.require(:loudnessmeasure).permit(:name, :obs, :url)

		{:state => 'queued', :name => params[:loudnessmeasure][:name], :obs => params[:loudnessmeasure][:obs], :url => params[:loudnessmeasure][:url], :user_id => current_user.id}
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  skip_before_action :authenticate_user!

  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loudnessmeasures_helper.rb
module LoudnessmeasuresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Loudness Meter</title>
  <link rel="stylesheet" href="/assets/bootstrap.css">
  <link rel="stylesheet" href="/assets/bootstrap-theme.css">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Online loudness meter</a>
	    </div>
	    <div class="collapse navbar-collapse">
	      	<ul class="nav navbar-nav">
	      		<%if user_signed_in?%>
	        	<li class="active"><%= link_to 'Upload new file to measure', new_loudnessmeasure_path %></li>
	        	<li class="active"><%= link_to 'See your measures', loudnessmeasures_path %></li>
	        	<%end%>
	        	<li class="active"><%= link_to 'About', pages_about_path %></li>
	      	</ul>
			<p class="navbar-text pull-right">
			<% if user_signed_in? %>
				Logged in as <strong><%= current_user.email %></strong>.
				<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
				<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
	    </div>
	  </div>
	</nav>	
	<div class="container">
		<% if notice %>
			<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
  			<p class="alert alert-danger"><%= alert %></p>
		<% end %>
  		<%= yield %>
	</div>
</body>
<footer>
  <div class="container">
    <a href="http://www.jordicenzano.name" target="_blank">Jordi Cenzano 2014</a>
  </div>
</footer>
</html>

app/views/loudnessmeasures/index.html.erb
<h1>Listing loudness measures</h1>
 
<table>
  <tr>
    <th>State</th>
    <th>Name</th>
    <th>Obs</th>
    <th>Filename</th>
    <th>Loudness I [LUFS]</th>
    <th>Loudness LRA [LU]</th>
  </tr>
 
  <% @loudnessmeasures.each do |loudnessmeasure| %>
    <tr>
      <td><%= loudnessmeasure.state %></td>
      <td><%= loudnessmeasure.name %></td>
      <td><%= loudnessmeasure.obs %></td>
      <td><%= loudnessmeasure.filename_plain %></td>
      <td><%= loudnessmeasure.loudnessi %></td>
      <td><%= loudnessmeasure.loudnesslra %></td>
      </tr>
  <% end %>
</table>
<%= link_to 'New measure', new_loudnessmeasure_path %>

app/views/loudnessmeasures/new.html.erb
<%= form_for :loudnessmeasure, url: loudnessmeasures_path , html: { id: "loudnessNew" } do |f| %>
  <% if @loudnessmeasure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loudnessmeasure.errors.count, "error") %> found</h2>
      <ul>
       <% @loudnessmeasure.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  <% end %> <p>
    <%= f.label 'Name' %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label 'Obs' %><br>
    <%= f.text_area :obs %>
  </p>

  <%= f.hidden_field :url  %>

 <script type="text/javascript">
    function check_params_and_show_error() {
      var strname = $('#loudnessmeasure_name').val();
      var strurl = $('#loudnessmeasure_url').val();
      var ret = false;

      if ((strname.trim() == "") && (strurl.trim() == ""))
        alert ("You have to enter a valid name and upload a media file first");
      else if ((strname.trim() == "") && (strurl.trim() != ""))
        alert ("You have to enter a valid name");
      else if ((strname.trim() != "") && (strurl.trim() == ""))
        alert ("You have to upload a media file first");
      else
        ret = true;

      return ret;
    }
  </script>
<% end %>

<%= s3_uploader_form id: "s3_uploader", max_file_size: 100.megabytes do %>

  <p>
    <%= file_field_tag :file, multiple: false %>
  </p>

  <script type="text/javascript">

    $(document).on("click","#loudnessmeasures_visible_submit",function(){
      if (check_params_and_show_error() == true)
      {
        $('#loudnessNew').submit();
      }
    });
  </script>

  <div id="uploads_container"></div>
  <script id="template-upload" type="text/x-tmpl">
    <div id="upload_{%=o.unique_id%}" class="upload">
      <h5>{%=o.name%}</h5>
      <div class="progress progress-striped active">
        <div class="bar" style="width: 0%"></div>
      </div>
    </div>
  </script>

<% end %>

<p id="loudnessmeasures_visible_submit">
  <%= button_tag "Add to loudness measure queue", type: 'button' %>
</p>

app/views/loudnessmeasures/show.html.erb
<p>
  <strong>State:</strong>
  <%= @loudnessmeasure.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @loudnessmeasure.name %>
</p>
 
<p>
  <strong>Obs:</strong>
  <%= @loudnessmeasure.obs %>
</p>

<strong>Original media file:</strong>
  <%= @loudnessmeasure.filename_plain %>
</p>

<%= link_to 'See loudness measures state', loudnessmeasures_path %>

app/views/pages/about.html.erb
<h1>Jordi Cenzano 2014</h1>
<p>I'm a developer specialized in video and audio processing and broadcast services, I developed this cloud service as an exercise to improve my knowledge of rails.</p>
<p>More info: <a href="http://www.jordicenzano.name" target="_blank">Personal page</a>, <script src="//platform.linkedin.com/in.js" type="text/javascript"></script><script type="IN/MemberProfile" data-id="https://www.linkedin.com/in/jordicenzano" data-format="hover" data-text="Jordi Cenzano" data-related="false"></script></p>

app/views/welcome/index.html.erb
<h1>This is a free cloud tool to measure the loudness (following EBU R128) of any media file.</h1>
<p>You only have to sign up an start upload your media files (the media is deleted after compute the loudness values)<p>
<p>The site code is available in github, as <a href="https://github.com/jordicenzano/OnlineLoudnessMeter" target="_blank">OnlineLoudnessMeter</a><p>
<p>The media decoding and loudness computing is powered by <a href="https://www.ffmpeg.org/" target="_blank">ffmpeg</a><p>